lpil/mix-test.watch

lib/mix_test_watch.ex
Awesome command! I saw your post on the mailing list and the only thing I had to add was the ability take the args and pass them to the test command. Just in case you only want to watch a subset of the tests.
=> Passing the args given to test.watch to passing them to the test command

lib/mix_test_watch.ex
Instead of having to save a file to trigger initial test run, this will run it once after startup.
=> Run tests upon start

lib/mix/tasks/test/watch.ex, lib/mix_test_watch/command.ex, test/mix_test_watch/command_test.exs
The commandline arguments seems to have been lost during some refactoring.
This commit restores the support to be able to run ```mix test.watch test/mix_test_watch/command_test.exs:15``` or  ```mix test.watch integration``` to be able to watch custom files and directories just like the normal mix `test` task.
=> Forward commandline arguments to command builder

lib/mix/tasks/test/watch.ex, lib/mix_test_watch/files.ex, lib/mix_test_watch/run.ex, mix.exs, test/mix_test_watch/files_test.exs, test/mix_test_watch/run_test.exs, test/support/mock_fs_helper.ex
When a watched test file is changed, run it with mix test. If the unix
error code is 0 (successful), run the complete suite.
When the file is not in the test directory, try to find a corresponding
test file following elixir conventions and run that instead.
This should speed up TDD extremely. Resolves lpil/mix-test.watch#12.
PS: I am new to elixir, so I might have missed some idioms. :angel: :goat:
=> on file change run single test first

README.md, lib/mix/tasks/test/watch.ex, lib/mix_test_watch/config.ex, test/mix_test_watch/config_test.exs
I like the option to have a clear console that only contains the results of the last test run.
This option clears the console before each  new run which you can set by adding
```
config :mix_test_watch, clear: true
```
to dev.exs.
Hope you will find this option as useful as I do :)
Gerard.
=> added an option to clear the console before run

lib/mix_test_watch/config.ex, lib/mix_test_watch/runner.ex, test/mix_test_watch/config_test.exs, test/mix_test_watch/runner_test.exs
This change will print a UTC timestamp after "Running Tests..." for each testing run.
=> Add optional timestamp printing

README.md
This will fix the error message reported in #28 . 
Manually tested in Phoenix 1.2, Elixir 1.2, Erlang 18 by using the global config.exs and the `if` check as well as without an `if` check inside the `config/dev.exs` file.
I'm not 100% satisfied with the comment verbiage so feel free to tweak it of course. Should at least help prevent confused folks.
Thanks for the hard work on this package btw... much appreciated 🍻
=> fixes :mix_test_watch warning

README.md
Provide `deps` examples for both Elixir 1.4 and earlier versions.
=> Include `runtime: false` for Elixir 1.4 dependency

lib/mix_test_watch/config.ex, test/mix_test_watch/config_test.exs
See #72. I propose adding excludes one commit at a time so it's easier to trace back what editor it is for.
=> Add default exclude for Emacs

mix.exs
phoenix_live_reload reverted fs to 0.9.1
https://github.com/phoenixframework/phoenix_live_reload/commit/e54bf6fb301436797ff589e0b76a047bb79b6870
----
Squashed commit of the following:
commit dbb8023d543154fb1fe60cb9676a3d4499ee84b5
Author: William Volin <williamvolin@live.com>
Date:   Sat Mar 18 20:49:53 2017 -0500
Update mix.exs
commit cdf812e271f7edd7dc5b753c5ed70a7a5cf25175
Author: William Volin <williamvolin@live.com>
Date:   Sat Mar 18 20:47:30 2017 -0500
Update mix.exs
fix fs version
-------------
This is a better PR than #75 (squashed, and up-to-date master)
=> fixes #61 (sort of) revert fs to 0.9.1

lib/mix_test_watch.ex, lib/mix_test_watch/watcher.ex, mix.exs, mix.lock
Fixes #68 with `file_system` instead of `fs`.
=> Remove fs dependency in favor of file_system

lib/mix_test_watch/port_runner/port_runner.ex, test/mix_test_watch/port_runner/port_runner_test.exs
a bit of context for this change: i was using `mix test --no-start` before i switched to this project. when i switched i noticed, that some of my tests failed due to `process xy is already running` errors which was suspicious because beside adding & using this project nothing else happened.
weeping through the code i found the relevant part in `PortRunner`. when executing
```bash
mix test.watch --no-start test/handler/types/entrypoint_test.exs
```
it gets transformed to the following command:
```bash
sh -c "MIX_ENV=test mix do run -e 'Application.put_env(:elixir, :ansi_enabled, true);', \
test --no-start test/handler/types/entrypoint_test.exs
```
where you can see, that it passes `--no-start` to the underlying `mix test` command, but it does not for the previous `mix run` command which is …
=> don't start application

README.md, lib/mix_test_watch/config.ex, test/mix_test_watch/config_test.exs
Add the default Phoenix migrations directory (`priv/repo/migrations`) to the default list of exclude regex patterns.
This addresses #52.
=> Add Phoenix Migrations Directory to Default Exclude Regex Patterns

README.md
Since in #95 @lpil suggested me to upgrade my version to the latest version, so I've found out that because I just copy the one in Usage section in the README.md, which is not up to date, I've got an older version. So I just update it just in case someone happens to face the same problem :D
=> Upgrade version in Usage section in README.md to "~> 0.8"

lib/mix_test_watch/port_runner/port_runner.ex, test/mix_test_watch/port_runner/port_runner_test.exs
since #87 broke some things (for example ecto, reported on #93) here's a new try that passes `--no-start` only along in case that the main script is called with that option.
given that it's opt-in, it should be fine this time and not break something else.
=> pass no-start option only if provided to main script

lib/mix_test_watch/port_runner/port_runner.ex, priv/zombie_killer
The `zombie_killer`  script was copied from the documentation in the Elixir lang Ports module (https://github.com/Javyre/elixir/blob/4da31098a84268d040e569590515744c02efb9cc/lib/elixir/lib/port.ex#L120).
See also https://github.com/elixir-lang/elixir/issues/9171.
Closes https://github.com/lpil/mix-test.watch/issues/100.
=> Add wrapper script to ensure no zombie processes

README.md
Closes #115 
As suggested in https://github.com/lpil/mix-test.watch/issues/115#issuecomment-759513881, this adds a reference to the new [mix_test_interactive](https://github.com/influxdata/mix_test_interactive) project as an alternative.
Thanks again for this project! I've used it so much, and it served as a great base for `mix_test_interactive`!
=> Add reference to mix_test_interactive

.gitignore, .travis.yml, README.md, mix.exs, mix.lock
Besides other changes, this commit ensures the generated HTML doc for
HexDocs.pm will become the main source doc for this Elixir library which
leverage on ExDoc features.
List of changes:
* Fix markdowns
* Set readme as main HTML page
* Add changelog to HTML page
* Tally minimum Elixir version with Travis CI
* Update license year
* Use common source url
* Add source reference
* Use and set latest ex_doc
* Badges and more badges!
* Revise content
* Update gitignore
Screenshot:
=> Misc doc changes

lib/mix_test_watch.ex, lib/mix_test_watch/watcher.ex
This is a minor fix for this deprecation warning.
=> Use the new child spec instead of deprecated Supervisor.Spec.worker/2

README.md
Matches up the default file extension list to the source.
=> Add `.heex` to default extension list in README.md

README.md
Dogma has been deprecated in favor of `mix format`. Credo, which is a library for static code analysis geared more towards coding style improvements rather than enforcing a style guide, makes more sense as an example in the documentation.
=> Replace references to Dogma with references to Credo

lib/mix_test_watch/watcher.ex
Hi 👋 
I noticed the following warning when I was compiling a project using 1.15.5. 
```shell
warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
lib/mix_test_watch/watcher.ex:38: MixTestWatch.Watcher.init/1
```
Seemed like a slam dunk so I made the change. Let me know if anything else is required.
P.S: commit message is wrong 😅
=> Fix `Logger.warn/1` deprecation warning in Elixir 1.15

CHANGELOG.md, lib/mix_test_watch/config.ex, mix.exs
Fixes #49 thanks to @danielspofford
Explanation here: https://github.com/lpil/mix-test.watch/issues/49#issuecomment-1848837003
=> Enable colored ouput by changing default_cli_executable
